POST http://localhost:3333/videos
Content-Type: application/json

{
    "title":"Node",
    "description":"Um projeto simples em node.js",
    "duration": 100
}

###

GET http://localhost:3333/videos?search=Node

###
GET http://localhost:3333/videos


###

PUT http://localhost:3333/videos/:id
Content-Type: application/json

{
    "title":"Node PUT",
    "description":"Um belo projeto CRUD em node.js",
    "duration": 100
}

###

DELETE http://localhost:3333/videos/:id
Content-Type: application/json