POST https://videos-api-xs85.onrender.com/videos
Content-Type: application/json

{
    "title":"Node",
    "description":"Um projeto simples em node.js",
    "duration": 100
}

###

GET https://videos-api-xs85.onrender.com/videos?search=Node

###
GET https://videos-api-xs85.onrender.com/videos


###

PUT https://videos-api-xs85.onrender.com/videos/:id
Content-Type: application/json

{
    "title":"Node PUT",
    "description":"Um belo projeto CRUD em node.js",
    "duration": 100
}

###

DELETE https://videos-api-xs85.onrender.com/videos/:id
Content-Type: application/json